In [1]:
import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import grangercausalitytests

In [17]:
root = r"C:\Users\mathe\Documents\Stanford\Stats 207\Final Project\granger-casusality-agro\Data"
commodities = pd.read_csv(root + "/commodities_prices.csv").iloc[:,1:]
commodities_f = pd.read_csv(root + "/commodities_prices_futures.csv").iloc[:,1:]
fires_state = pd.read_csv(root + "/n_fires_times_series.csv").iloc[:,1:]
fires_national = pd.read_csv(root + "/n_fires_time_series_national.csv")#.iloc[:,1:]

In [36]:
# Merge two datasets
fires_commodities = fires_national.merge(commodities, left_on = 'date', right_on ='DATE').drop('date', axis = 1)

In [37]:
fires_commodities

fires        DATE         beef       coffee          soy         corn  \
0     3551  1998-06-01    89.432015   146.207311   266.779496   117.451980   
1     8067  1998-07-01    88.193812   135.815631   269.940852   117.190463   
2    35551  1998-08-01    89.188690   144.877357   236.974377   103.529312   
3    41976  1998-09-01    88.593719   133.330499   228.234447   101.185905   
4    23499  1998-10-01    88.289975   130.050529   238.678185   113.533719   
..     ...         ...          ...          ...          ...          ...   
287   6698  2022-05-01  1335.545591  1292.220420  3061.855605  1711.267490   
288   7876  2022-06-01  1326.742057  1381.876707  3135.622044  1694.599377   
289  14212  2022-07-01  1383.078386  1373.758168  3065.250103  1678.539738   
290  47507  2022-08-01  1295.604296  1380.112472  2965.106961  1510.921835   
291  60313  2022-09-01  1293.143264  1402.622481  2818.707563  1638.866876   

         sugar  EXBZUS  
0     9.348256  1.1543  
1    10.016798  1.1614  
2     9.938806  1.1717  
3     8.533942  1.1805  
4     8.872436  1.1889  
..         ...     ...  
287  95.662230  4.9615  
288  94.866933  5.0477  
289  98.452788  5.3682  
290  92.849034  5.1404  
291  95.359633  5.2436  

[292 rows x 8 columns]

# Granger Causality Tests (Spot Prices)

In [42]:
# Beef
grangercausalitytests(fires_commodities[['fires', 'beef']], maxlag=[3])


Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.7268  , p=0.5367  , df_denom=282, df_num=3
ssr based chi2 test:   chi2=2.2347  , p=0.5252  , df=3
likelihood ratio test: chi2=2.2261  , p=0.5268  , df=3
parameter F test:         F=0.7268  , p=0.5367  , df_denom=282, df_num=3


{3: ({'ssr_ftest': (0.7268461838562242, 0.5366921639213433, 282.0, 3),
   'ssr_chi2test': (2.234665395047328, 0.5251526837079126, 3),
   'lrtest': (2.226070005021029, 0.526831664247478, 3),
   'params_ftest': (0.7268461838562154, 0.5366921639213433, 282.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.]])])}

In [43]:
# Corn
grangercausalitytests(fires_commodities[['fires', 'corn']], maxlag=[3])


Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.3312  , p=0.2644  , df_denom=282, df_num=3
ssr based chi2 test:   chi2=4.0927  , p=0.2516  , df=3
likelihood ratio test: chi2=4.0640  , p=0.2546  , df=3
parameter F test:         F=1.3312  , p=0.2644  , df_denom=282, df_num=3


{3: ({'ssr_ftest': (1.3311866592038273, 0.26444253515636335, 282.0, 3),
   'ssr_chi2test': (4.092690899041554, 0.25162757165253036, 3),
   'lrtest': (4.0639821774830125, 0.254637579293492, 3),
   'params_ftest': (1.3311866592038675, 0.26444253515635624, 282.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.]])])}

In [44]:
# Sugar
grangercausalitytests(fires_commodities[['fires', 'sugar']], maxlag=[3])


Granger Causality
number of lags (no zero) 3
ssr based F test:         F=2.0352  , p=0.1091  , df_denom=282, df_num=3
ssr based chi2 test:   chi2=6.2572  , p=0.0997  , df=3
likelihood ratio test: chi2=6.1904  , p=0.1027  , df=3
parameter F test:         F=2.0352  , p=0.1091  , df_denom=282, df_num=3


{3: ({'ssr_ftest': (2.03520468095978, 0.10914890300781042, 282.0, 3),
   'ssr_chi2test': (6.2571718382699615, 0.09974703066387818, 3),
   'lrtest': (6.190396588839576, 0.10270564560803973, 3),
   'params_ftest': (2.035204680959831, 0.10914890300780089, 282.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.]])])}

In [45]:
# Coffee
grangercausalitytests(fires_commodities[['fires', 'coffee']], maxlag=[3])


Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.5105  , p=0.6754  , df_denom=282, df_num=3
ssr based chi2 test:   chi2=1.5695  , p=0.6663  , df=3
likelihood ratio test: chi2=1.5653  , p=0.6673  , df=3
parameter F test:         F=0.5105  , p=0.6754  , df_denom=282, df_num=3


{3: ({'ssr_ftest': (0.5105000407998619, 0.6753502366062617, 282.0, 3),
   'ssr_chi2test': (1.5695160828846815, 0.6663214231461254, 3),
   'lrtest': (1.5652695464341377, 0.6672900996527893, 3),
   'params_ftest': (0.51050004079988, 0.6753502366062472, 282.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.]])])}

In [46]:
# Soy
grangercausalitytests(fires_commodities[['fires', 'soy']], maxlag=[3])


Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.3492  , p=0.2587  , df_denom=282, df_num=3
ssr based chi2 test:   chi2=4.1482  , p=0.2459  , df=3
likelihood ratio test: chi2=4.1187  , p=0.2489  , df=3
parameter F test:         F=1.3492  , p=0.2587  , df_denom=282, df_num=3


{3: ({'ssr_ftest': (1.3492485461946873, 0.2586619703535822, 282.0, 3),
   'ssr_chi2test': (4.148221594151751, 0.24589728324253934, 3),
   'lrtest': (4.118732266030747, 0.2489253217378368, 3),
   'params_ftest': (1.3492485461947157, 0.25866197035356653, 282.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.]])])}

# Granger Causality Tests (Future Prices)

In [18]:
# Merge two datasets
fires_commodities_futures = fires_national.merge(commodities_f, left_on = 'date', right_on ='Date').drop('Date', axis = 1)

In [19]:
# Beef
grangercausalitytests(fires_commodities_futures[['fires', 'f_beef']], maxlag=[3])


Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.4618  , p=0.7092  , df_denom=282, df_num=3
ssr based chi2 test:   chi2=1.4197  , p=0.7009  , df=3
likelihood ratio test: chi2=1.4162  , p=0.7017  , df=3
parameter F test:         F=0.4618  , p=0.7092  , df_denom=282, df_num=3


{3: ({'ssr_ftest': (0.46177029052588614, 0.7092037350608094, 282.0, 3),
   'ssr_chi2test': (1.4196980208721393, 0.7009239711668387, 3),
   'lrtest': (1.4162223013900075, 0.7017365782661671, 3),
   'params_ftest': (0.4617702905258927, 0.7092037350607945, 282.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.]])])}

In [20]:
# Corn
grangercausalitytests(fires_commodities_futures[['fires', 'f_corn']], maxlag=[3])


Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.6017  , p=0.6144  , df_denom=282, df_num=3
ssr based chi2 test:   chi2=1.8501  , p=0.6041  , df=3
likelihood ratio test: chi2=1.8442  , p=0.6054  , df=3
parameter F test:         F=0.6017  , p=0.6144  , df_denom=282, df_num=3


{3: ({'ssr_ftest': (0.6017466300124396, 0.6143539922809163, 282.0, 3),
   'ssr_chi2test': (1.8500508092935644, 0.604104351003788, 3),
   'lrtest': (1.8441543547214678, 0.6053739110367358, 3),
   'params_ftest': (0.6017466300124534, 0.6143539922809163, 282.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.]])])}

In [21]:
# Sugar
grangercausalitytests(fires_commodities_futures[['fires', 'f_sugar']], maxlag=[3])


Granger Causality
number of lags (no zero) 3
ssr based F test:         F=5.4272  , p=0.0012  , df_denom=282, df_num=3
ssr based chi2 test:   chi2=16.6856 , p=0.0008  , df=3
likelihood ratio test: chi2=16.2217 , p=0.0010  , df=3
parameter F test:         F=5.4272  , p=0.0012  , df_denom=282, df_num=3


{3: ({'ssr_ftest': (5.427162561840838, 0.0012133244166585265, 282.0, 3),
   'ssr_chi2test': (16.685638089063854, 0.000820130634091877, 3),
   'lrtest': (16.22173162962281, 0.0010212487042462744, 3),
   'params_ftest': (5.427162561840817, 0.0012133244166585492, 282.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.]])])}

In [22]:
# Coffee
grangercausalitytests(fires_commodities_futures[['fires', 'f_coffee']], maxlag=[3])


Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.6369  , p=0.5918  , df_denom=282, df_num=3
ssr based chi2 test:   chi2=1.9582  , p=0.5811  , df=3
likelihood ratio test: chi2=1.9516  , p=0.5825  , df=3
parameter F test:         F=0.6369  , p=0.5918  , df_denom=282, df_num=3


{3: ({'ssr_ftest': (0.6369246481512533, 0.5917832965392767, 282.0, 3),
   'ssr_chi2test': (1.9582045033586404, 0.58112667420706, 3),
   'lrtest': (1.9516001245592633, 0.5825128007208489, 3),
   'params_ftest': (0.6369246481512504, 0.5917832965392767, 282.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.]])])}

In [23]:
# Soy
grangercausalitytests(fires_commodities_futures[['fires', 'f_soy']], maxlag=[3])


Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.1142  , p=0.3436  , df_denom=282, df_num=3
ssr based chi2 test:   chi2=3.4257  , p=0.3305  , df=3
likelihood ratio test: chi2=3.4056  , p=0.3332  , df=3
parameter F test:         F=1.1142  , p=0.3436  , df_denom=282, df_num=3


{3: ({'ssr_ftest': (1.1142428134797844, 0.3436337148305664, 282.0, 3),
   'ssr_chi2test': (3.425703969102742, 0.33052667353465176, 3),
   'lrtest': (3.405559460728, 0.33321887687001955, 3),
   'params_ftest': (1.1142428134807292, 0.3436337148301731, 282.0, 3.0)},
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.]])])}

In [ ]:
# Transform data to be stationary using cofounders (VAR), run stationary test and then apply Granger Causality
# Check Granger causality for all of the prices together and add cofounders (one test)
# Apply LASSO method and compare 
# Validate Granger causality - why does p-value increases as the number of lags increases?
# Push to github
# How to extend this to states (panel level?) (Leave for it later)